config/routes.rb
Rails.application.routes.draw do
  get "about-us", to: "about#index", as: :about
 

get "password", to:"passwords#edit", as: :edit_password
patch "password", to: "passwords#update"

  get "sign_up", to: "registrations#new"
  post "sign_up", to: "registrations#create"

  get "sign_in", to: "sessions#new"
  post "sign_in", to: "sessions#create"

  delete "logout", to: "sessions#destroy"
  
  resources :gossips
  root to: "gossips#index"

  get '/login', to: 'sessions#new', as: 'new_session'
  post '/login', to: 'sessions#create', as: 'session'
  delete '/logout', to: 'sessions#destroy', as: 'destroy_session'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/current.rb
class Current < ActiveSupport::CurrentAttributes
  attribute :user
end

app/models/gossip.rb
class Gossip < ApplicationRecord
  belongs_to :user
  validates :content, presence: true
end

app/models/user.rb
#email:string
#password_digest:string
#
#password:string virtual
#password_confirmation:string virtual 




class User < ApplicationRecord
  has_secure_password
  validates :email, presence: true, format: { with: /\A[^@\s]+@[^@\s]+\z/, message: "must be invalid email" }
  
  has_many :gossips
  validates :username, presence: true, uniqueness: true
  validates :email, presence: true, uniqueness: true
end

app/controllers/about_controller.rb
class AboutController < ApplicationController
  def index
    
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
before_action :set_current_user
helper_method :current_user
before_action :authenticate_user! # Vérifier que l'utilisateur est connecté
before_action :set_current_user
protect_from_forgery with: :exception

  def set_current_user
    if session[:user_id]
      Current.user = User.find(session[:user_id])
    end
  end

  def require_user_logged_in!
    redirect_to sign_in_path, alert: "You must be signed in to do that." if Current.user.nil?
  end

  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end

  private

  def authenticate_user!
    redirect_to new_session_path, alert: "Vous devez vous connecter pour accéder à cette page." unless user_signed_in?
  end

  def user_signed_in?
    current_user.present?
  end

end

app/controllers/gossips_controller.rb
class GossipsController < ApplicationController
  before_action :set_gossip, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!, only: [:new, :create, :edit, :update, :destroy]
  
  def authenticate_user!
    redirect_to new_session_path, alert: "Vous devez vous connecter pour accéder à cette page." unless user_signed_in?
  end

  def index
    @gossips = Gossip.all
  end

  def show
  end

  def new
    @gossip = Gossip.new
  end

  def create
    @gossip = Gossip.new(gossip_params)

    if @gossip.save
      redirect_to @gossip, notice: 'Gossip was successfully created.'
    else
      render :new
    end
  end

  def edit
  end

  def update
    if @gossip.update(gossip_params)
      redirect_to @gossip, notice: 'Gossip was successfully updated.'
    else
      render :edit
    end
  end

  def destroy
    @gossip.destroy
    redirect_to gossips_url, notice: 'Gossip was successfully destroyed.'
  end

  private

  def set_gossip
    @gossip = Gossip.find(params[:id])
  end

  def gossip_params
    params.require(:gossip).permit(:content, :user_id)
  end
end

app/controllers/passwords_controller.rb
class PasswordsController < ApplicationController
  before_action :require_user_logged_in!
  
  def edit

  end

  def update
  if Current.user.update(password_params)
    redirect_to root_path, notice: "Password updated!"
  else
    render :edit, status: :unprocessable_entity
  end

  private

  def password_params
    params.require(:user).permit(:password, :password_confirmation)
  end
end
end

app/controllers/registrations_controller.rb
class RegistrationsController < ApplicationController
  cattr_accessor :current
  
  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      session[:user_id] = @user.id
      redirect_to root_path, notice: "Successfully created account"
    else
      render :new, status: :unprocessable_entity
    end
  end

  private
  def user_params
    params.require(:user).permit(:email, :password, :password_confirmation)
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  
  def new
    @gossip = Gossip.new
    @user = current_user # vérifier que current_user est initialisée
  end

  def create
    user = User.find_by(email: params[:email])
    if user.present? && user.authenticate(params[:password])
      session[:user_id] = user.id
      redirect_to root_path, notice: "Logged in successfully"
    else
      flash[:alert] = "Invalid email or password"
      render :new, status: :unprocessable_entity
    end
  end
  
  
  
  def destroy
    session[:user_id] = nil
    redirect_to root_path, notice: "Logged out"
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/menus_helper.rb
module MenusHelper
end

app/views/about/index.html.erb
<h1>About Us</h1>

app/views/gossips/edit.html.erb
<h1>Editing Gossip</h1>

<%= render 'shared/form', gossip: @gossip %>

<%= link_to 'Show', @gossip %> |
<%= link_to 'Back', gossips_path %>

app/views/gossips/index.html.erb
<div class="d-flex align-items-center justify-content-center">

<h1>Bienvenue</h1>
</div>

<h1>Gossips</h1>

<table>
  <thead>
    <tr>
      <th>User</th>
      <th>Content</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @gossips.each do |gossip| %>
      <tr>
        <td><%= gossip.user.username %></td>
        <td><%= gossip.content %></td>
        <td><%= link_to 'Show', gossip %></td>
        <% if current_user == gossip.user %>
          <td><%= link_to 'Edit', edit_gossip_path(gossip) %></td>
          <td><%= link_to 'Destroy', gossip, method: :delete, data: { confirm: 'Are you sure?' } %></td>
        <% end %>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Gossip', new_gossip_path %>

app/views/gossips/new.html.erb
<h1>New Gossip</h1>

<%= render 'shared/form', gossip: @gossip %>

<%= link_to 'Back', gossips_path %>

app/views/gossips/show.html.erb
<p>
  <strong>User:</strong>
  <%= @gossip.user.username %>
</p>

<p>
  <strong>Content:</strong>
  <%= @gossip.content %>
</p>

<% if current_user == @gossip.user %>
  <%= link_to 'Edit', edit_gossip_path(@gossip) %> |
  <%= link_to 'Back', gossips_path %>
<% else %>
  <%= link_to 'Back', gossips_path %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ProjectGossip</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.0.0/dist/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">

<script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/popper.js@1.12.9/dist/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@4.0.0/dist/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
<%= render partial: "shared/navbar"%>
  
  <div class="container">
  <%= render partial: "shared/flash"%>
    <%= yield %>
    </div>
  </body>
</html>

app/views/shared/_flash.html.erb
<% if flash[:notice]%>
  <div class="alert alert-info" role="alert">
    <%= flash[:notice]%>
  </div>
<% end %>

<% if flash[:alert]%>
  <div class="alert alert-warning" role="alert">
   <%= flash[:alert]%>
  </div>
<% end %>

app/views/shared/_form.html.erb
<%= form_with(model: gossip, local: true) do |form| %>
  <% if gossip.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(gossip.errors.count, "error") %> prohibited this gossip from being saved:</h2>

      <ul>
        <% gossip.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :content %>
    <%= form.text_area :content %>
  </div>

  <%= form.hidden_field :user_id, value: current_user.id %>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/shared/_navbar.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <%= link_to "The Gossip Porject", root_path, class: "navbar-brand"%>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse" id="navbarNav">
    <ul class="navbar-nav">
      <li class="nav-item active">
        <%= link_to "Home", root_path, class: "nav-link"%>
      </li>
      <li class="nav-item">
      <%= link_to "About", about_path, class: "nav-link"%>
      </li>
    </ul>  
  </div>
  <ul class="navbar-nav ms-auto mb-2 mb-lg-0">
<% if Current.user %>
<li class="nav-item">
<%= link_to Current.user.email, edit_password_path, class: "nav-link"%>
</li>
<li class="nav-item">
<%= button_to "Logout", logout_path, method: :delete, class: "btn btn-outline-secondary" %>
</li>
<% else %>
<li class="nav-item">
<%= link_to "Sign Up", sign_up_path, class: "nav-link"%>
</li>
<li class="nav-item">
<%= link_to "Login", sign_in_path, class: "nav-link"%>
</li>
<% end %>
</ul>
</nav>